var searchData=
[
  ['rawcodecoveragedata_2ephp_0',['RawCodeCoverageData.php',['../_raw_code_coverage_data_8php.html',1,'']]],
  ['reader_2ephp_1',['Reader.php',['../_reader_8php.html',1,'']]],
  ['readme_2emd_2',['README.md',['../myclabs_2deep-copy_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../nikic_2php-parser_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../phar-io_2manifest_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../phar-io_2version_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../phpunit_2php-code-coverage_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../phpunit_2php-file-iterator_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../phpunit_2php-invoker_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../phpunit_2php-text-template_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../phpunit_2php-timer_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2cli-parser_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2code-unit-reverse-lookup_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2code-unit_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2comparator_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2complexity_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2diff_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2environment_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2exporter_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2global-state_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2lines-of-code_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2object-enumerator_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2object-reflector_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2recursion-context_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2type_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../sebastian_2version_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../theseer_2tokenizer_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)']]],
  ['readonlyfunctiontokenemulator_2ephp_3',['ReadonlyFunctionTokenEmulator.php',['../_readonly_function_token_emulator_8php.html',1,'']]],
  ['readonlytokenemulator_2ephp_4',['ReadonlyTokenEmulator.php',['../_readonly_token_emulator_8php.html',1,'']]],
  ['reflection_2ephp_5',['Reflection.php',['../_reflection_8php.html',1,'']]],
  ['reflectionexception_2ephp_6',['ReflectionException.php',['../phpunit_2php-code-coverage_2src_2_exception_2_reflection_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_framework_2_mock_object_2_generator_2_exception_2_reflection_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_metadata_2_exception_2_reflection_exception_8php.html',1,'(Global Namespace)'],['../sebastian_2code-unit_2src_2exceptions_2_reflection_exception_8php.html',1,'(Global Namespace)']]],
  ['reflectionhelper_2ephp_7',['ReflectionHelper.php',['../_reflection_helper_8php.html',1,'']]],
  ['reflectionmapper_2ephp_8',['ReflectionMapper.php',['../_reflection_mapper_8php.html',1,'']]],
  ['registry_2ephp_9',['Registry.php',['../_metadata_2_parser_2_annotation_2_registry_8php.html',1,'(Global Namespace)'],['../_metadata_2_parser_2_registry_8php.html',1,'(Global Namespace)'],['../_text_u_i_2_configuration_2_registry_8php.html',1,'(Global Namespace)']]],
  ['regularexpression_2ephp_10',['RegularExpression.php',['../_regular_expression_8php.html',1,'']]],
  ['relative_2ephp_11',['Relative.php',['../_relative_8php.html',1,'']]],
  ['relativepathcalculator_2ephp_12',['RelativePathCalculator.php',['../_relative_path_calculator_8php.html',1,'']]],
  ['removebestrictaboutresourceusageduringsmalltestsattribute_2ephp_13',['RemoveBeStrictAboutResourceUsageDuringSmallTestsAttribute.php',['../_remove_be_strict_about_resource_usage_during_small_tests_attribute_8php.html',1,'']]],
  ['removebestrictabouttodoannotatedtestsattribute_2ephp_14',['RemoveBeStrictAboutTodoAnnotatedTestsAttribute.php',['../_remove_be_strict_about_todo_annotated_tests_attribute_8php.html',1,'']]],
  ['removecacheresultfileattribute_2ephp_15',['RemoveCacheResultFileAttribute.php',['../_remove_cache_result_file_attribute_8php.html',1,'']]],
  ['removecachetokensattribute_2ephp_16',['RemoveCacheTokensAttribute.php',['../_remove_cache_tokens_attribute_8php.html',1,'']]],
  ['removeconversiontoexceptionsattributes_2ephp_17',['RemoveConversionToExceptionsAttributes.php',['../_remove_conversion_to_exceptions_attributes_8php.html',1,'']]],
  ['removecoverageelementcachedirectoryattribute_2ephp_18',['RemoveCoverageElementCacheDirectoryAttribute.php',['../_remove_coverage_element_cache_directory_attribute_8php.html',1,'']]],
  ['removecoverageelementincludeuncoveredfilesattribute_2ephp_19',['RemoveCoverageElementIncludeUncoveredFilesAttribute.php',['../_remove_coverage_element_include_uncovered_files_attribute_8php.html',1,'']]],
  ['removecoverageelementprocessuncoveredfilesattribute_2ephp_20',['RemoveCoverageElementProcessUncoveredFilesAttribute.php',['../_remove_coverage_element_process_uncovered_files_attribute_8php.html',1,'']]],
  ['removeemptyfilter_2ephp_21',['RemoveEmptyFilter.php',['../_remove_empty_filter_8php.html',1,'']]],
  ['removelisteners_2ephp_22',['RemoveListeners.php',['../_remove_listeners_8php.html',1,'']]],
  ['removeloggingelements_2ephp_23',['RemoveLoggingElements.php',['../_remove_logging_elements_8php.html',1,'']]],
  ['removelogtypes_2ephp_24',['RemoveLogTypes.php',['../_remove_log_types_8php.html',1,'']]],
  ['removenointeractionattribute_2ephp_25',['RemoveNoInteractionAttribute.php',['../_remove_no_interaction_attribute_8php.html',1,'']]],
  ['removeprinterattributes_2ephp_26',['RemovePrinterAttributes.php',['../_remove_printer_attributes_8php.html',1,'']]],
  ['removeregistermockobjectsfromtestargumentsrecursivelyattribute_2ephp_27',['RemoveRegisterMockObjectsFromTestArgumentsRecursivelyAttribute.php',['../_remove_register_mock_objects_from_test_arguments_recursively_attribute_8php.html',1,'']]],
  ['removetestdoxgroupselement_2ephp_28',['RemoveTestDoxGroupsElement.php',['../_remove_test_dox_groups_element_8php.html',1,'']]],
  ['removetestsuiteloaderattributes_2ephp_29',['RemoveTestSuiteLoaderAttributes.php',['../_remove_test_suite_loader_attributes_8php.html',1,'']]],
  ['removeverboseattribute_2ephp_30',['RemoveVerboseAttribute.php',['../_remove_verbose_attribute_8php.html',1,'']]],
  ['renamebackupstaticattributesattribute_2ephp_31',['RenameBackupStaticAttributesAttribute.php',['../_rename_backup_static_attributes_attribute_8php.html',1,'']]],
  ['renamebestrictaboutcoversannotationattribute_2ephp_32',['RenameBeStrictAboutCoversAnnotationAttribute.php',['../_rename_be_strict_about_covers_annotation_attribute_8php.html',1,'']]],
  ['renameforcecoversannotationattribute_2ephp_33',['RenameForceCoversAnnotationAttribute.php',['../_rename_force_covers_annotation_attribute_8php.html',1,'']]],
  ['renderer_2ephp_34',['Renderer.php',['../_renderer_8php.html',1,'']]],
  ['reorderable_2ephp_35',['Reorderable.php',['../_reorderable_8php.html',1,'']]],
  ['replacefilter_2ephp_36',['ReplaceFilter.php',['../_filter_2_replace_filter_8php.html',1,'(Global Namespace)'],['../_type_filter_2_replace_filter_8php.html',1,'(Global Namespace)']]],
  ['replacerestrictdeprecationswithignoredeprecations_2ephp_37',['ReplaceRestrictDeprecationsWithIgnoreDeprecations.php',['../_replace_restrict_deprecations_with_ignore_deprecations_8php.html',1,'']]],
  ['report_2ephp_38',['Report.php',['../_report_8php.html',1,'']]],
  ['reportalreadyfinalizedexception_2ephp_39',['ReportAlreadyFinalizedException.php',['../_report_already_finalized_exception_8php.html',1,'']]],
  ['requiredoptionargumentmissingexception_2ephp_40',['RequiredOptionArgumentMissingException.php',['../_required_option_argument_missing_exception_8php.html',1,'']]],
  ['requirement_2ephp_41',['Requirement.php',['../phar-io_2manifest_2src_2values_2_requirement_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_metadata_2_version_2_requirement_8php.html',1,'(Global Namespace)']]],
  ['requirementcollection_2ephp_42',['RequirementCollection.php',['../_requirement_collection_8php.html',1,'']]],
  ['requirementcollectioniterator_2ephp_43',['RequirementCollectionIterator.php',['../_requirement_collection_iterator_8php.html',1,'']]],
  ['requirements_2ephp_44',['Requirements.php',['../_requirements_8php.html',1,'']]],
  ['requireselement_2ephp_45',['RequiresElement.php',['../_requires_element_8php.html',1,'']]],
  ['requiresfunction_2ephp_46',['RequiresFunction.php',['../_framework_2_attributes_2_requires_function_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_function_8php.html',1,'(Global Namespace)']]],
  ['requiresmethod_2ephp_47',['RequiresMethod.php',['../_framework_2_attributes_2_requires_method_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_method_8php.html',1,'(Global Namespace)']]],
  ['requiresoperatingsystem_2ephp_48',['RequiresOperatingSystem.php',['../_framework_2_attributes_2_requires_operating_system_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_operating_system_8php.html',1,'(Global Namespace)']]],
  ['requiresoperatingsystemfamily_2ephp_49',['RequiresOperatingSystemFamily.php',['../_framework_2_attributes_2_requires_operating_system_family_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_operating_system_family_8php.html',1,'(Global Namespace)']]],
  ['requiresphp_2ephp_50',['RequiresPhp.php',['../_framework_2_attributes_2_requires_php_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_php_8php.html',1,'(Global Namespace)']]],
  ['requiresphpextension_2ephp_51',['RequiresPhpExtension.php',['../_framework_2_attributes_2_requires_php_extension_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_php_extension_8php.html',1,'(Global Namespace)']]],
  ['requiresphpunit_2ephp_52',['RequiresPhpunit.php',['../_framework_2_attributes_2_requires_phpunit_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_phpunit_8php.html',1,'(Global Namespace)']]],
  ['requiresphpunitextension_2ephp_53',['RequiresPhpunitExtension.php',['../_framework_2_attributes_2_requires_phpunit_extension_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_phpunit_extension_8php.html',1,'(Global Namespace)']]],
  ['requiressetting_2ephp_54',['RequiresSetting.php',['../_framework_2_attributes_2_requires_setting_8php.html',1,'(Global Namespace)'],['../_metadata_2_requires_setting_8php.html',1,'(Global Namespace)']]],
  ['resourcecomparator_2ephp_55',['ResourceComparator.php',['../_resource_comparator_8php.html',1,'']]],
  ['resourceusageformatter_2ephp_56',['ResourceUsageFormatter.php',['../_resource_usage_formatter_8php.html',1,'']]],
  ['restorer_2ephp_57',['Restorer.php',['../_restorer_8php.html',1,'']]],
  ['result_2ephp_58',['Result.php',['../_text_u_i_2_command_2_result_8php.html',1,'(Global Namespace)'],['../_util_2_p_h_p_2_result_8php.html',1,'(Global Namespace)']]],
  ['resultcache_2ephp_59',['ResultCache.php',['../_result_cache_8php.html',1,'']]],
  ['resultcachehandler_2ephp_60',['ResultCacheHandler.php',['../_result_cache_handler_8php.html',1,'']]],
  ['resultprinter_2ephp_61',['ResultPrinter.php',['../_default_2_result_printer_8php.html',1,'(Global Namespace)'],['../_test_dox_2_result_printer_8php.html',1,'(Global Namespace)']]],
  ['return_5f_2ephp_62',['Return_.php',['../_return___8php.html',1,'']]],
  ['returnargument_2ephp_63',['ReturnArgument.php',['../_return_argument_8php.html',1,'']]],
  ['returncallback_2ephp_64',['ReturnCallback.php',['../_return_callback_8php.html',1,'']]],
  ['returnreference_2ephp_65',['ReturnReference.php',['../_return_reference_8php.html',1,'']]],
  ['returnself_2ephp_66',['ReturnSelf.php',['../_return_self_8php.html',1,'']]],
  ['returnstub_2ephp_67',['ReturnStub.php',['../_return_stub_8php.html',1,'']]],
  ['returnvaluegenerator_2ephp_68',['ReturnValueGenerator.php',['../_return_value_generator_8php.html',1,'']]],
  ['returnvaluemap_2ephp_69',['ReturnValueMap.php',['../_return_value_map_8php.html',1,'']]],
  ['returnvaluenotconfiguredexception_2ephp_70',['ReturnValueNotConfiguredException.php',['../_return_value_not_configured_exception_8php.html',1,'']]],
  ['reverseemulator_2ephp_71',['ReverseEmulator.php',['../_reverse_emulator_8php.html',1,'']]],
  ['risky_2ephp_72',['Risky.php',['../_risky_8php.html',1,'']]],
  ['runclassinseparateprocess_2ephp_73',['RunClassInSeparateProcess.php',['../_framework_2_attributes_2_run_class_in_separate_process_8php.html',1,'(Global Namespace)'],['../_metadata_2_run_class_in_separate_process_8php.html',1,'(Global Namespace)']]],
  ['runinseparateprocess_2ephp_74',['RunInSeparateProcess.php',['../_framework_2_attributes_2_run_in_separate_process_8php.html',1,'(Global Namespace)'],['../_metadata_2_run_in_separate_process_8php.html',1,'(Global Namespace)']]],
  ['runtestsinseparateprocesses_2ephp_75',['RunTestsInSeparateProcesses.php',['../_framework_2_attributes_2_run_tests_in_separate_processes_8php.html',1,'(Global Namespace)'],['../_metadata_2_run_tests_in_separate_processes_8php.html',1,'(Global Namespace)']]],
  ['runtime_2ephp_76',['Runtime.php',['../phpunit_2phpunit_2src_2_event_2_value_2_runtime_2_runtime_8php.html',1,'(Global Namespace)'],['../sebastian_2environment_2src_2_runtime_8php.html',1,'(Global Namespace)']]],
  ['runtimeexception_2ephp_77',['RuntimeException.php',['../phpunit_2php-text-template_2src_2exceptions_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_event_2_exception_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_framework_2_mock_object_2_exception_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_framework_2_mock_object_2_generator_2_exception_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_text_u_i_2_exception_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../sebastian_2comparator_2src_2exceptions_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../sebastian_2complexity_2src_2_exception_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../sebastian_2global-state_2src_2exceptions_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../sebastian_2lines-of-code_2src_2_exception_2_runtime_exception_8php.html',1,'(Global Namespace)'],['../sebastian_2type_2src_2exception_2_runtime_exception_8php.html',1,'(Global Namespace)']]]
];
