var searchData=
[
  ['cachewarmer_2ephp_0',['CacheWarmer.php',['../_cache_warmer_8php.html',1,'']]],
  ['cachingfileanalyser_2ephp_1',['CachingFileAnalyser.php',['../_caching_file_analyser_8php.html',1,'']]],
  ['cachingparser_2ephp_2',['CachingParser.php',['../_caching_parser_8php.html',1,'']]],
  ['calculator_2ephp_3',['Calculator.php',['../_calculator_8php.html',1,'']]],
  ['callabletype_2ephp_4',['CallableType.php',['../_callable_type_8php.html',1,'']]],
  ['callback_2ephp_5',['Callback.php',['../_callback_8php.html',1,'']]],
  ['calllike_2ephp_6',['CallLike.php',['../_call_like_8php.html',1,'']]],
  ['cannotclonetestdoubleforreadonlyclassexception_2ephp_7',['CannotCloneTestDoubleForReadonlyClassException.php',['../_cannot_clone_test_double_for_readonly_class_exception_8php.html',1,'']]],
  ['cannotfindschemaexception_2ephp_8',['CannotFindSchemaException.php',['../_cannot_find_schema_exception_8php.html',1,'']]],
  ['cannotloadbaselineexception_2ephp_9',['CannotLoadBaselineException.php',['../_cannot_load_baseline_exception_8php.html',1,'']]],
  ['cannotopensocketexception_2ephp_10',['CannotOpenSocketException.php',['../_cannot_open_socket_exception_8php.html',1,'']]],
  ['cannotuseaddmethodsexception_2ephp_11',['CannotUseAddMethodsException.php',['../_cannot_use_add_methods_exception_8php.html',1,'']]],
  ['cannotuseonlymethodsexception_2ephp_12',['CannotUseOnlyMethodsException.php',['../_cannot_use_only_methods_exception_8php.html',1,'']]],
  ['case_5f_2ephp_13',['Case_.php',['../_case___8php.html',1,'']]],
  ['cast_2ephp_14',['Cast.php',['../_cast_8php.html',1,'']]],
  ['catch_5f_2ephp_15',['Catch_.php',['../_catch___8php.html',1,'']]],
  ['chainablefilter_2ephp_16',['ChainableFilter.php',['../_chainable_filter_8php.html',1,'']]],
  ['changelog_2d11_2e0_2emd_17',['ChangeLog-11.0.md',['../_change_log-11_80_8md.html',1,'']]],
  ['changelog_2d11_2e4_2emd_18',['ChangeLog-11.4.md',['../_change_log-11_84_8md.html',1,'']]],
  ['changelog_2emd_19',['CHANGELOG.md',['../phar-io_2manifest_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../phar-io_2version_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../theseer_2tokenizer_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)']]],
  ['changelog_2emd_20',['ChangeLog.md',['../phpunit_2php-file-iterator_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../phpunit_2php-invoker_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../phpunit_2php-text-template_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../phpunit_2php-timer_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2cli-parser_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2code-unit-reverse-lookup_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2code-unit_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2comparator_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2complexity_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2diff_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2environment_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2exporter_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2global-state_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2lines-of-code_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2object-enumerator_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2object-reflector_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2recursion-context_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2type_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)'],['../sebastian_2version_2_c_h_a_n_g_e_l_o_g_8md.html',1,'(Global Namespace)']]],
  ['chunk_2ephp_21',['Chunk.php',['../_chunk_8php.html',1,'']]],
  ['class_5f_2ephp_22',['Class_.php',['../_builder_2_class___8php.html',1,'(Global Namespace)'],['../_node_2_scalar_2_magic_const_2_class___8php.html',1,'(Global Namespace)'],['../_node_2_stmt_2_class___8php.html',1,'(Global Namespace)']]],
  ['classcannotbefoundexception_2ephp_23',['ClassCannotBeFoundException.php',['../_class_cannot_be_found_exception_8php.html',1,'']]],
  ['classconst_2ephp_24',['ClassConst.php',['../_builder_2_class_const_8php.html',1,'(Global Namespace)'],['../_node_2_stmt_2_class_const_8php.html',1,'(Global Namespace)']]],
  ['classconstfetch_2ephp_25',['ClassConstFetch.php',['../_class_const_fetch_8php.html',1,'']]],
  ['classdoesnotextendtestcaseexception_2ephp_26',['ClassDoesNotExtendTestCaseException.php',['../_class_does_not_extend_test_case_exception_8php.html',1,'']]],
  ['classisabstractexception_2ephp_27',['ClassIsAbstractException.php',['../_class_is_abstract_exception_8php.html',1,'']]],
  ['classisenumerationexception_2ephp_28',['ClassIsEnumerationException.php',['../_class_is_enumeration_exception_8php.html',1,'']]],
  ['classisfinalexception_2ephp_29',['ClassIsFinalException.php',['../_class_is_final_exception_8php.html',1,'']]],
  ['classlike_2ephp_30',['ClassLike.php',['../_class_like_8php.html',1,'']]],
  ['classloader_2ephp_31',['ClassLoader.php',['../_class_loader_8php.html',1,'']]],
  ['classmethod_2ephp_32',['ClassMethod.php',['../nikic_2php-parser_2lib_2_php_parser_2_node_2_stmt_2_class_method_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_event_2_value_2_class_method_8php.html',1,'(Global Namespace)']]],
  ['classmethodunit_2ephp_33',['ClassMethodUnit.php',['../_class_method_unit_8php.html',1,'']]],
  ['classunit_2ephp_34',['ClassUnit.php',['../_class_unit_8php.html',1,'']]],
  ['clone_5f_2ephp_35',['Clone_.php',['../_clone___8php.html',1,'']]],
  ['cloneexception_2ephp_36',['CloneException.php',['../_clone_exception_8php.html',1,'']]],
  ['cloner_2ephp_37',['Cloner.php',['../_cloner_8php.html',1,'']]],
  ['cloningvisitor_2ephp_38',['CloningVisitor.php',['../_cloning_visitor_8php.html',1,'']]],
  ['closure_2ephp_39',['Closure.php',['../_closure_8php.html',1,'']]],
  ['closureuse_2ephp_40',['ClosureUse.php',['../_closure_use_8php.html',1,'(Global Namespace)'],['../_expr_2_closure_use_8php.html',1,'(Global Namespace)']]],
  ['clover_2ephp_41',['Clover.php',['../php-code-coverage_2src_2_report_2_clover_8php.html',1,'(Global Namespace)'],['../phpunit_2src_2_text_u_i_2_configuration_2_xml_2_code_coverage_2_report_2_clover_8php.html',1,'(Global Namespace)']]],
  ['coalesce_2ephp_42',['Coalesce.php',['../_assign_op_2_coalesce_8php.html',1,'(Global Namespace)'],['../_binary_op_2_coalesce_8php.html',1,'(Global Namespace)']]],
  ['cobertura_2ephp_43',['Cobertura.php',['../php-code-coverage_2src_2_report_2_cobertura_8php.html',1,'(Global Namespace)'],['../phpunit_2src_2_text_u_i_2_configuration_2_xml_2_code_coverage_2_report_2_cobertura_8php.html',1,'(Global Namespace)']]],
  ['codecoverage_2ephp_44',['CodeCoverage.php',['../php-code-coverage_2src_2_code_coverage_8php.html',1,'(Global Namespace)'],['../phpunit_2src_2_metadata_2_api_2_code_coverage_8php.html',1,'(Global Namespace)'],['../phpunit_2src_2_runner_2_code_coverage_8php.html',1,'(Global Namespace)'],['../phpunit_2src_2_text_u_i_2_configuration_2_xml_2_code_coverage_2_code_coverage_8php.html',1,'(Global Namespace)']]],
  ['codecoverageexception_2ephp_45',['CodeCoverageException.php',['../_code_coverage_exception_8php.html',1,'']]],
  ['codecoveragefilterregistry_2ephp_46',['CodeCoverageFilterRegistry.php',['../_code_coverage_filter_registry_8php.html',1,'']]],
  ['codecoveragereportnotconfiguredexception_2ephp_47',['CodeCoverageReportNotConfiguredException.php',['../_code_coverage_report_not_configured_exception_8php.html',1,'']]],
  ['codeexporter_2ephp_48',['CodeExporter.php',['../_code_exporter_8php.html',1,'']]],
  ['codeunit_2ephp_49',['CodeUnit.php',['../_code_unit_8php.html',1,'']]],
  ['codeunitcollection_2ephp_50',['CodeUnitCollection.php',['../_code_unit_collection_8php.html',1,'']]],
  ['codeunitcollectioniterator_2ephp_51',['CodeUnitCollectionIterator.php',['../_code_unit_collection_iterator_8php.html',1,'']]],
  ['codeunitfindingvisitor_2ephp_52',['CodeUnitFindingVisitor.php',['../_code_unit_finding_visitor_8php.html',1,'']]],
  ['collecting_2ephp_53',['Collecting.php',['../_collecting_8php.html',1,'']]],
  ['collectingdispatcher_2ephp_54',['CollectingDispatcher.php',['../_collecting_dispatcher_8php.html',1,'']]],
  ['collector_2ephp_55',['Collector.php',['../_deprecation_collector_2_collector_8php.html',1,'(Global Namespace)'],['../_test_result_2_collector_8php.html',1,'(Global Namespace)']]],
  ['color_2ephp_56',['Color.php',['../_color_8php.html',1,'']]],
  ['colors_2ephp_57',['Colors.php',['../_colors_8php.html',1,'']]],
  ['command_2ephp_58',['Command.php',['../_command_8php.html',1,'']]],
  ['comment_2ephp_59',['Comment.php',['../_comment_8php.html',1,'']]],
  ['commentannotatingvisitor_2ephp_60',['CommentAnnotatingVisitor.php',['../_comment_annotating_visitor_8php.html',1,'']]],
  ['comparator_2ephp_61',['Comparator.php',['../_comparator_8php.html',1,'']]],
  ['comparatorregistered_2ephp_62',['ComparatorRegistered.php',['../_comparator_registered_8php.html',1,'']]],
  ['comparatorregisteredsubscriber_2ephp_63',['ComparatorRegisteredSubscriber.php',['../_comparator_registered_subscriber_8php.html',1,'']]],
  ['comparisonfailure_2ephp_64',['ComparisonFailure.php',['../phpunit_2phpunit_2src_2_event_2_value_2_comparison_failure_8php.html',1,'(Global Namespace)'],['../sebastian_2comparator_2src_2_comparison_failure_8php.html',1,'(Global Namespace)']]],
  ['comparisonfailurebuilder_2ephp_65',['ComparisonFailureBuilder.php',['../_comparison_failure_builder_8php.html',1,'']]],
  ['comparisonmethoddoesnotacceptparametertypeexception_2ephp_66',['ComparisonMethodDoesNotAcceptParameterTypeException.php',['../_comparison_method_does_not_accept_parameter_type_exception_8php.html',1,'']]],
  ['comparisonmethoddoesnotdeclareboolreturntypeexception_2ephp_67',['ComparisonMethodDoesNotDeclareBoolReturnTypeException.php',['../_comparison_method_does_not_declare_bool_return_type_exception_8php.html',1,'']]],
  ['comparisonmethoddoesnotdeclareexactlyoneparameterexception_2ephp_68',['ComparisonMethodDoesNotDeclareExactlyOneParameterException.php',['../_comparison_method_does_not_declare_exactly_one_parameter_exception_8php.html',1,'']]],
  ['comparisonmethoddoesnotdeclareparametertypeexception_2ephp_69',['ComparisonMethodDoesNotDeclareParameterTypeException.php',['../_comparison_method_does_not_declare_parameter_type_exception_8php.html',1,'']]],
  ['comparisonmethoddoesnotexistexception_2ephp_70',['ComparisonMethodDoesNotExistException.php',['../_comparison_method_does_not_exist_exception_8php.html',1,'']]],
  ['comparisonrequirement_2ephp_71',['ComparisonRequirement.php',['../_comparison_requirement_8php.html',1,'']]],
  ['compatibility_5ftokens_2ephp_72',['compatibility_tokens.php',['../compatibility__tokens_8php.html',1,'']]],
  ['complexity_2ephp_73',['Complexity.php',['../_complexity_8php.html',1,'']]],
  ['complexitycalculatingvisitor_2ephp_74',['ComplexityCalculatingVisitor.php',['../_complexity_calculating_visitor_8php.html',1,'']]],
  ['complexitycollection_2ephp_75',['ComplexityCollection.php',['../_complexity_collection_8php.html',1,'']]],
  ['complexitycollectioniterator_2ephp_76',['ComplexityCollectionIterator.php',['../_complexity_collection_iterator_8php.html',1,'']]],
  ['complextype_2ephp_77',['ComplexType.php',['../_complex_type_8php.html',1,'']]],
  ['componentelement_2ephp_78',['ComponentElement.php',['../_component_element_8php.html',1,'']]],
  ['componentelementcollection_2ephp_79',['ComponentElementCollection.php',['../_component_element_collection_8php.html',1,'']]],
  ['concat_2ephp_80',['Concat.php',['../_assign_op_2_concat_8php.html',1,'(Global Namespace)'],['../_binary_op_2_concat_8php.html',1,'(Global Namespace)']]],
  ['configurablemethod_2ephp_81',['ConfigurableMethod.php',['../_configurable_method_8php.html',1,'']]],
  ['configuration_2ephp_82',['Configuration.php',['../_cli_2_configuration_8php.html',1,'(Global Namespace)'],['../_configuration_8php.html',1,'(Global Namespace)'],['../_xml_2_configuration_8php.html',1,'(Global Namespace)']]],
  ['configurationcannotbebuiltexception_2ephp_83',['ConfigurationCannotBeBuiltException.php',['../_configuration_cannot_be_built_exception_8php.html',1,'']]],
  ['configurationexception_2ephp_84',['ConfigurationException.php',['../_configuration_exception_8php.html',1,'']]],
  ['configured_2ephp_85',['Configured.php',['../_configured_8php.html',1,'']]],
  ['configuredsubscriber_2ephp_86',['ConfiguredSubscriber.php',['../_configured_subscriber_8php.html',1,'']]],
  ['consecutivecalls_2ephp_87',['ConsecutiveCalls.php',['../_consecutive_calls_8php.html',1,'']]],
  ['consideredrisky_2ephp_88',['ConsideredRisky.php',['../_considered_risky_8php.html',1,'']]],
  ['consideredriskysubscriber_2ephp_89',['ConsideredRiskySubscriber.php',['../_considered_risky_subscriber_8php.html',1,'']]],
  ['console_2ephp_90',['Console.php',['../_console_8php.html',1,'']]],
  ['const_5f_2ephp_91',['Const_.php',['../_const___8php.html',1,'(Global Namespace)'],['../_stmt_2_const___8php.html',1,'(Global Namespace)']]],
  ['constant_2ephp_92',['Constant.php',['../_constant_8php.html',1,'']]],
  ['constantcollection_2ephp_93',['ConstantCollection.php',['../_constant_collection_8php.html',1,'']]],
  ['constantcollectioniterator_2ephp_94',['ConstantCollectionIterator.php',['../_constant_collection_iterator_8php.html',1,'']]],
  ['constexprevaluationexception_2ephp_95',['ConstExprEvaluationException.php',['../_const_expr_evaluation_exception_8php.html',1,'']]],
  ['constexprevaluator_2ephp_96',['ConstExprEvaluator.php',['../_const_expr_evaluator_8php.html',1,'']]],
  ['constfetch_2ephp_97',['ConstFetch.php',['../_const_fetch_8php.html',1,'']]],
  ['constraint_2ephp_98',['Constraint.php',['../_constraint_8php.html',1,'']]],
  ['constraintrequirement_2ephp_99',['ConstraintRequirement.php',['../_constraint_requirement_8php.html',1,'']]],
  ['containselement_2ephp_100',['ContainsElement.php',['../_contains_element_8php.html',1,'']]],
  ['context_2ephp_101',['Context.php',['../_context_8php.html',1,'']]],
  ['continue_5f_2ephp_102',['Continue_.php',['../_continue___8php.html',1,'']]],
  ['convertlogtypes_2ephp_103',['ConvertLogTypes.php',['../_convert_log_types_8php.html',1,'']]],
  ['copyrightelement_2ephp_104',['CopyrightElement.php',['../_copyright_element_8php.html',1,'']]],
  ['copyrightinformation_2ephp_105',['CopyrightInformation.php',['../_copyright_information_8php.html',1,'']]],
  ['count_2ephp_106',['Count.php',['../_count_8php.html',1,'']]],
  ['counter_2ephp_107',['Counter.php',['../_counter_8php.html',1,'']]],
  ['coverage_2ephp_108',['Coverage.php',['../_coverage_8php.html',1,'']]],
  ['coverageclovertoreport_2ephp_109',['CoverageCloverToReport.php',['../_coverage_clover_to_report_8php.html',1,'']]],
  ['coveragecrap4jtoreport_2ephp_110',['CoverageCrap4jToReport.php',['../_coverage_crap4j_to_report_8php.html',1,'']]],
  ['coveragehtmltoreport_2ephp_111',['CoverageHtmlToReport.php',['../_coverage_html_to_report_8php.html',1,'']]],
  ['coveragephptoreport_2ephp_112',['CoveragePhpToReport.php',['../_coverage_php_to_report_8php.html',1,'']]],
  ['coveragetexttoreport_2ephp_113',['CoverageTextToReport.php',['../_coverage_text_to_report_8php.html',1,'']]],
  ['coveragexmltoreport_2ephp_114',['CoverageXmlToReport.php',['../_coverage_xml_to_report_8php.html',1,'']]],
  ['covers_2ephp_115',['Covers.php',['../_covers_8php.html',1,'']]],
  ['coversclass_2ephp_116',['CoversClass.php',['../_framework_2_attributes_2_covers_class_8php.html',1,'(Global Namespace)'],['../_metadata_2_covers_class_8php.html',1,'(Global Namespace)']]],
  ['coversdefaultclass_2ephp_117',['CoversDefaultClass.php',['../_covers_default_class_8php.html',1,'']]],
  ['coversfunction_2ephp_118',['CoversFunction.php',['../_framework_2_attributes_2_covers_function_8php.html',1,'(Global Namespace)'],['../_metadata_2_covers_function_8php.html',1,'(Global Namespace)']]],
  ['coversmethod_2ephp_119',['CoversMethod.php',['../_framework_2_attributes_2_covers_method_8php.html',1,'(Global Namespace)'],['../_metadata_2_covers_method_8php.html',1,'(Global Namespace)']]],
  ['coversnothing_2ephp_120',['CoversNothing.php',['../_framework_2_attributes_2_covers_nothing_8php.html',1,'(Global Namespace)'],['../_metadata_2_covers_nothing_8php.html',1,'(Global Namespace)']]],
  ['coverstrait_2ephp_121',['CoversTrait.php',['../_framework_2_attributes_2_covers_trait_8php.html',1,'(Global Namespace)'],['../_metadata_2_covers_trait_8php.html',1,'(Global Namespace)']]],
  ['crap4j_2ephp_122',['Crap4j.php',['../php-code-coverage_2src_2_report_2_crap4j_8php.html',1,'(Global Namespace)'],['../phpunit_2src_2_text_u_i_2_configuration_2_xml_2_code_coverage_2_report_2_crap4j_8php.html',1,'(Global Namespace)']]],
  ['crapindex_2ephp_123',['CrapIndex.php',['../_crap_index_8php.html',1,'']]],
  ['customcssfile_2ephp_124',['CustomCssFile.php',['../_custom_css_file_8php.html',1,'']]],
  ['cyclomaticcomplexitycalculatingvisitor_2ephp_125',['CyclomaticComplexityCalculatingVisitor.php',['../_cyclomatic_complexity_calculating_visitor_8php.html',1,'']]]
];
