var searchData=
[
  ['identical_2ephp_0',['Identical.php',['../_identical_8php.html',1,'']]],
  ['identifier_2ephp_1',['Identifier.php',['../_identifier_8php.html',1,'']]],
  ['identity_2ephp_2',['Identity.php',['../_identity_8php.html',1,'']]],
  ['if_5f_2ephp_3',['If_.php',['../_if___8php.html',1,'']]],
  ['ignoredeprecations_2ephp_4',['IgnoreDeprecations.php',['../_framework_2_attributes_2_ignore_deprecations_8php.html',1,'(Global Namespace)'],['../_metadata_2_ignore_deprecations_8php.html',1,'(Global Namespace)']]],
  ['ignoredlinesfindingvisitor_2ephp_5',['IgnoredLinesFindingVisitor.php',['../_ignored_lines_finding_visitor_8php.html',1,'']]],
  ['ignorephpunitdeprecations_2ephp_6',['IgnorePhpunitDeprecations.php',['../_framework_2_attributes_2_ignore_phpunit_deprecations_8php.html',1,'(Global Namespace)'],['../_metadata_2_ignore_phpunit_deprecations_8php.html',1,'(Global Namespace)']]],
  ['illogicalvaluesexception_2ephp_7',['IllogicalValuesException.php',['../_illogical_values_exception_8php.html',1,'']]],
  ['include_5f_2ephp_8',['Include_.php',['../_include___8php.html',1,'']]],
  ['includegroupfilteriterator_2ephp_9',['IncludeGroupFilterIterator.php',['../_include_group_filter_iterator_8php.html',1,'']]],
  ['includenamefilteriterator_2ephp_10',['IncludeNameFilterIterator.php',['../_include_name_filter_iterator_8php.html',1,'']]],
  ['incompatiblereturnvalueexception_2ephp_11',['IncompatibleReturnValueException.php',['../_incompatible_return_value_exception_8php.html',1,'']]],
  ['incomplete_2ephp_12',['Incomplete.php',['../_incomplete_8php.html',1,'']]],
  ['incompletetest_2ephp_13',['IncompleteTest.php',['../_incomplete_test_8php.html',1,'']]],
  ['incompletetesterror_2ephp_14',['IncompleteTestError.php',['../_incomplete_test_error_8php.html',1,'']]],
  ['indirecttrigger_2ephp_15',['IndirectTrigger.php',['../_indirect_trigger_8php.html',1,'']]],
  ['info_2ephp_16',['Info.php',['../_info_8php.html',1,'']]],
  ['inisetting_2ephp_17',['IniSetting.php',['../_ini_setting_8php.html',1,'']]],
  ['inisettingcollection_2ephp_18',['IniSettingCollection.php',['../_ini_setting_collection_8php.html',1,'']]],
  ['inisettingcollectioniterator_2ephp_19',['IniSettingCollectionIterator.php',['../_ini_setting_collection_iterator_8php.html',1,'']]],
  ['inlinehtml_2ephp_20',['InlineHTML.php',['../_inline_h_t_m_l_8php.html',1,'']]],
  ['installed_2ephp_21',['installed.php',['../installed_8php.html',1,'']]],
  ['installedversions_2ephp_22',['InstalledVersions.php',['../_installed_versions_8php.html',1,'']]],
  ['instanceof_5f_2ephp_23',['Instanceof_.php',['../_instanceof___8php.html',1,'']]],
  ['int_5f_2ephp_24',['Int_.php',['../_expr_2_cast_2_int___8php.html',1,'(Global Namespace)'],['../_scalar_2_int___8php.html',1,'(Global Namespace)']]],
  ['interface_5f_2ephp_25',['Interface_.php',['../_builder_2_interface___8php.html',1,'(Global Namespace)'],['../_node_2_stmt_2_interface___8php.html',1,'(Global Namespace)']]],
  ['interfacemethodunit_2ephp_26',['InterfaceMethodUnit.php',['../_interface_method_unit_8php.html',1,'']]],
  ['interfaceunit_2ephp_27',['InterfaceUnit.php',['../_interface_unit_8php.html',1,'']]],
  ['interpolatedstring_2ephp_28',['InterpolatedString.php',['../_interpolated_string_8php.html',1,'']]],
  ['interpolatedstringpart_2ephp_29',['InterpolatedStringPart.php',['../_interpolated_string_part_8php.html',1,'']]],
  ['intersectiontype_2ephp_30',['IntersectionType.php',['../nikic_2php-parser_2lib_2_php_parser_2_node_2_intersection_type_8php.html',1,'(Global Namespace)'],['../sebastian_2type_2src_2type_2_intersection_type_8php.html',1,'(Global Namespace)']]],
  ['introducecachedirectoryattribute_2ephp_31',['IntroduceCacheDirectoryAttribute.php',['../_introduce_cache_directory_attribute_8php.html',1,'']]],
  ['introducecoverageelement_2ephp_32',['IntroduceCoverageElement.php',['../_introduce_coverage_element_8php.html',1,'']]],
  ['invalidapplicationnameexception_2ephp_33',['InvalidApplicationNameException.php',['../_invalid_application_name_exception_8php.html',1,'']]],
  ['invalidargumentexception_2ephp_34',['InvalidArgumentException.php',['../phpunit_2php-code-coverage_2src_2_exception_2_invalid_argument_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2php-text-template_2src_2exceptions_2_invalid_argument_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_event_2_exception_2_invalid_argument_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit_2src_2_framework_2_exception_2_invalid_argument_exception_8php.html',1,'(Global Namespace)'],['../sebastian_2diff_2src_2_exception_2_invalid_argument_exception_8php.html',1,'(Global Namespace)']]],
  ['invalidcodeunitexception_2ephp_35',['InvalidCodeUnitException.php',['../_invalid_code_unit_exception_8php.html',1,'']]],
  ['invalidcoverstargetexception_2ephp_36',['InvalidCoversTargetException.php',['../_invalid_covers_target_exception_8php.html',1,'']]],
  ['invaliddataproviderexception_2ephp_37',['InvalidDataProviderException.php',['../_invalid_data_provider_exception_8php.html',1,'']]],
  ['invaliddependencyexception_2ephp_38',['InvalidDependencyException.php',['../_invalid_dependency_exception_8php.html',1,'']]],
  ['invaliddirectoryexception_2ephp_39',['InvalidDirectoryException.php',['../_invalid_directory_exception_8php.html',1,'']]],
  ['invalidemailexception_2ephp_40',['InvalidEmailException.php',['../_invalid_email_exception_8php.html',1,'']]],
  ['invalideventexception_2ephp_41',['InvalidEventException.php',['../_invalid_event_exception_8php.html',1,'']]],
  ['invalidjsonexception_2ephp_42',['InvalidJsonException.php',['../_invalid_json_exception_8php.html',1,'']]],
  ['invalidmethodnameexception_2ephp_43',['InvalidMethodNameException.php',['../_invalid_method_name_exception_8php.html',1,'']]],
  ['invalidorderexception_2ephp_44',['InvalidOrderException.php',['../_invalid_order_exception_8php.html',1,'']]],
  ['invalidphptfileexception_2ephp_45',['InvalidPhptFileException.php',['../_invalid_phpt_file_exception_8php.html',1,'']]],
  ['invalidprereleasesuffixexception_2ephp_46',['InvalidPreReleaseSuffixException.php',['../_invalid_pre_release_suffix_exception_8php.html',1,'']]],
  ['invalidsocketexception_2ephp_47',['InvalidSocketException.php',['../_invalid_socket_exception_8php.html',1,'']]],
  ['invalidsubscriberexception_2ephp_48',['InvalidSubscriberException.php',['../_invalid_subscriber_exception_8php.html',1,'']]],
  ['invalidurlexception_2ephp_49',['InvalidUrlException.php',['../_invalid_url_exception_8php.html',1,'']]],
  ['invalidversionexception_2ephp_50',['InvalidVersionException.php',['../_invalid_version_exception_8php.html',1,'']]],
  ['invalidversionoperatorexception_2ephp_51',['InvalidVersionOperatorException.php',['../_invalid_version_operator_exception_8php.html',1,'']]],
  ['invalidversionrequirementexception_2ephp_52',['InvalidVersionRequirementException.php',['../_invalid_version_requirement_exception_8php.html',1,'']]],
  ['invocation_2ephp_53',['Invocation.php',['../_invocation_8php.html',1,'']]],
  ['invocationhandler_2ephp_54',['InvocationHandler.php',['../_invocation_handler_8php.html',1,'']]],
  ['invocationmocker_2ephp_55',['InvocationMocker.php',['../_invocation_mocker_8php.html',1,'']]],
  ['invocationorder_2ephp_56',['InvocationOrder.php',['../_invocation_order_8php.html',1,'']]],
  ['invocationstubber_2ephp_57',['InvocationStubber.php',['../_invocation_stubber_8php.html',1,'']]],
  ['invokedatleastcount_2ephp_58',['InvokedAtLeastCount.php',['../_invoked_at_least_count_8php.html',1,'']]],
  ['invokedatleastonce_2ephp_59',['InvokedAtLeastOnce.php',['../_invoked_at_least_once_8php.html',1,'']]],
  ['invokedatmostcount_2ephp_60',['InvokedAtMostCount.php',['../_invoked_at_most_count_8php.html',1,'']]],
  ['invokedcount_2ephp_61',['InvokedCount.php',['../_invoked_count_8php.html',1,'']]],
  ['invoker_2ephp_62',['Invoker.php',['../_invoker_8php.html',1,'']]],
  ['isanything_2ephp_63',['IsAnything.php',['../_is_anything_8php.html',1,'']]],
  ['isempty_2ephp_64',['IsEmpty.php',['../_is_empty_8php.html',1,'']]],
  ['isequal_2ephp_65',['IsEqual.php',['../_is_equal_8php.html',1,'']]],
  ['isequalcanonicalizing_2ephp_66',['IsEqualCanonicalizing.php',['../_is_equal_canonicalizing_8php.html',1,'']]],
  ['isequalignoringcase_2ephp_67',['IsEqualIgnoringCase.php',['../_is_equal_ignoring_case_8php.html',1,'']]],
  ['isequalwithdelta_2ephp_68',['IsEqualWithDelta.php',['../_is_equal_with_delta_8php.html',1,'']]],
  ['isfalse_2ephp_69',['IsFalse.php',['../_is_false_8php.html',1,'']]],
  ['isfinite_2ephp_70',['IsFinite.php',['../_is_finite_8php.html',1,'']]],
  ['isidentical_2ephp_71',['IsIdentical.php',['../_is_identical_8php.html',1,'']]],
  ['isinfinite_2ephp_72',['IsInfinite.php',['../_is_infinite_8php.html',1,'']]],
  ['isinstanceof_2ephp_73',['IsInstanceOf.php',['../_is_instance_of_8php.html',1,'']]],
  ['isjson_2ephp_74',['IsJson.php',['../_is_json_8php.html',1,'']]],
  ['islist_2ephp_75',['IsList.php',['../_is_list_8php.html',1,'']]],
  ['isnan_2ephp_76',['IsNan.php',['../_is_nan_8php.html',1,'']]],
  ['isnull_2ephp_77',['IsNull.php',['../_is_null_8php.html',1,'']]],
  ['isolatedtestrunner_2ephp_78',['IsolatedTestRunner.php',['../_isolated_test_runner_8php.html',1,'']]],
  ['isolatedtestrunnerregistry_2ephp_79',['IsolatedTestRunnerRegistry.php',['../_isolated_test_runner_registry_8php.html',1,'']]],
  ['isreadable_2ephp_80',['IsReadable.php',['../_is_readable_8php.html',1,'']]],
  ['isset_5f_2ephp_81',['Isset_.php',['../_isset___8php.html',1,'']]],
  ['issue_2ephp_82',['Issue.php',['../_baseline_2_issue_8php.html',1,'(Global Namespace)'],['../_test_result_2_issue_8php.html',1,'(Global Namespace)']]],
  ['issuefilter_2ephp_83',['IssueFilter.php',['../_issue_filter_8php.html',1,'']]],
  ['issuetrigger_2ephp_84',['IssueTrigger.php',['../_issue_trigger_8php.html',1,'']]],
  ['istrue_2ephp_85',['IsTrue.php',['../_is_true_8php.html',1,'']]],
  ['istype_2ephp_86',['IsType.php',['../_is_type_8php.html',1,'']]],
  ['iswritable_2ephp_87',['IsWritable.php',['../_is_writable_8php.html',1,'']]],
  ['iterabletype_2ephp_88',['IterableType.php',['../_iterable_type_8php.html',1,'']]],
  ['iterator_2ephp_89',['Iterator.php',['../php-code-coverage_2src_2_node_2_iterator_8php.html',1,'(Global Namespace)'],['../php-file-iterator_2src_2_iterator_8php.html',1,'(Global Namespace)']]]
];
